// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPqZRdDU7zoLwOER-74Xpbt7xUzJvtT7g',
    appId: '1:135543249973:web:ff987d0a535fc55488257c',
    messagingSenderId: '135543249973',
    projectId: 'world-news-ccd2c',
    authDomain: 'world-news-ccd2c.firebaseapp.com',
    storageBucket: 'world-news-ccd2c.appspot.com',
    measurementId: 'G-MRMYHVNEXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc78r72cbL78g6JHJQX0uKOTiDlajQS54',
    appId: '1:135543249973:android:fce1d63f4967dbd588257c',
    messagingSenderId: '135543249973',
    projectId: 'world-news-ccd2c',
    storageBucket: 'world-news-ccd2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUJZJN7pMNjH2ZBD9yI0SHZ-0Ovto6dYU',
    appId: '1:135543249973:ios:5c6197851fb26f4288257c',
    messagingSenderId: '135543249973',
    projectId: 'world-news-ccd2c',
    storageBucket: 'world-news-ccd2c.appspot.com',
    iosBundleId: 'com.example.worldNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUJZJN7pMNjH2ZBD9yI0SHZ-0Ovto6dYU',
    appId: '1:135543249973:ios:5c6197851fb26f4288257c',
    messagingSenderId: '135543249973',
    projectId: 'world-news-ccd2c',
    storageBucket: 'world-news-ccd2c.appspot.com',
    iosBundleId: 'com.example.worldNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPqZRdDU7zoLwOER-74Xpbt7xUzJvtT7g',
    appId: '1:135543249973:web:fc69c19f63912a2088257c',
    messagingSenderId: '135543249973',
    projectId: 'world-news-ccd2c',
    authDomain: 'world-news-ccd2c.firebaseapp.com',
    storageBucket: 'world-news-ccd2c.appspot.com',
    measurementId: 'G-GWEYV2DBML',
  );

}